apiVersion: v1
kind: policy
metadata:
  name: allow-hostaccess
spec:
  selector: all()
  ingress:
  - action: allow 
    protocol: tcp
    source:
      net: {{ dcos_subnet }}
    destination:
      net: 172.16.0.0/16

  - action: allow 
    protocol: icmp
    source:
      net: {{ dcos_subnet }}
    destination:
      net: 172.16.0.0/16

  egress:
  - action: allow
