---
- name: test..
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - { role: calico-network, when: "dcos_node_type == 'master'"}
    - { role: test, when: mount_snapshot is defined }

