---
- name: restart server
  shell: shutdown -r now "Reboot triggered by Ansible"
  async: 0
  poll: 0
  ignore_errors: true

- name: wait for server to restart
  wait_for_connection:
    timeout: 120
    delay: 2

