apiVersion: v1
kind: policy
metadata:
  name: gearman-policy
spec:
  selector: role == 'gearman'
  ingress:
  - action: allow 
    protocol: tcp
    destination:
      ports:
      - 4730
  egress:
  - action: allow
