apiVersion: v1
kind: policy
metadata:
  name: memcache-policy
spec:
  selector: all()
  ingress:
  - action: allow 
    protocol: tcp
    destination:
      ports:
      - 11211
  egress:
  - action: allow
