apiVersion: v1
kind: policy

metadata:
  name: allow-postgres

spec:
  selector: all()

  ingress:
  - action: allow 
    protocol: tcp
    source:
      net: 172.16.110.0/24
    destination:
      net: 172.16.100.0/24
      ports: 
      - 5432
  
  egress:
  - action: allow
