---
- name: get ec2 details
  ec2_facts:

- name: debug ec2 instanceid
  debug: var=ansible_ec2_instance_id

- name: install boto
  yum: name={{ item }} state=present
  with_items:
    - python2-boto

- name: create volume from snapshot
  ec2_vol:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    device_name: /dev/sdf
    snapshot: "{{ mount_snapshot }}"
    volume_type: gp2
    state: present
    instance: "{{ ansible_ec2_instance_id }}"
    region: "{{ ansible_ec2_placement_availability_zone[0:-1] }}"
    tags: 
      Name: "{{ volume_name }}"


- name: mount new volumne
  mount:
    path: /mnt/data
    src: /dev/xvdf
    fstype: ext4
    state: mounted
