---
- name: test a variable
  debug: var=inventory_hostname


- name: upgrade all packages
  yum: 
    name: '*'
    state: latest


- name: install dcos pre-requisites
  yum: name={{ item }} state=present
  with_items:
    - unzip
    - ipset
    - epel-release


- name: install jq
  yum: name={{ item }} state=present
  with_items:
    - jq


- name: set selinux to permissive mode
  replace:
    dest: /etc/selinux/config
    regexp: '^SELINUX=enforcing'
    replace: 'SELINUX=permissive'
  notify:
    - restart server
    - wait for server to restart


- name: create new group
  group:
    name: nogroup
    state: present


- name: add directory for shared mount
  file:
    path: /mnt/shared_data
    state: directory


- name: add nfs mount to fstab
  lineinfile:
    path: /etc/fstab
    line: "{{ nfs_url }}:/ /mnt/shared_data nfs4 nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2 0 0"

- name: trigger handlers
  meta: flush_handlers 
