---
- name: yum-utils
  yum:
    name: yum-utils
    state: present

- name: update docker repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo


- name: enable overlay fs
  copy:
    src: overlay.conf
    dest: /etc/modules-load.d


- name: mkdir for docker service override
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory


- name: add docker config overrides 
  template:
    src: override.conf
    dest: /etc/systemd/system/docker.service.d/override.conf


- name: add directory for docker ssl certificates
  file:
    path: /etc/docker/ssl/
    state: directory


- name: copy docker ssl certificates
  copy:
    src: "ssl/{{ item }}"
    dest: /etc/docker/ssl/
  with_items:
    - ca.pem
    - cert.pem
    - key.pem


- name: install docker-ce
  yum:
   name: docker-ce
   state: present


- name: start docker
  systemd:
   daemon_reload: yes
   name: docker.service
   state: started
   enabled: yes


- name: netfilter 
  sysctl:
    name: net.netfilter.nf_conntrack_tcp_be_liberal
    value: 1
    state: present
    sysctl_set: yes
  notify:
    - restart server
    - wait for server to restart
