---
- name: create calico config directories
  file: 
    path: /opt/configs/
    state: directory


- name: copy calico policies configurations
  copy: 
    src: policy-postgres.yaml
    dest: /opt/configs/


- name: copy calico policies configurations
  template: 
    src: "{{ item }}"
    dest: /opt/configs/
  with_items:
    - policy-hostaccess.yaml
    - ippool-caliconet.yaml


- name: add calico frontend network ip pool
  command: calicoctl apply -f /opt/configs/ippool-caliconet.yaml


- name: add caliconet docker network
  docker_network:
    name: caliconet
    driver: calico
    ipam_driver: calico-ipam
    ipam_options:
      subnet: "{{ caliconet_subnet }}"
    state: present


- name: add calico permission to allow docker hosts to access containers directly 
  command: calicoctl apply -f /opt/configs/policy-hostaccess.yaml


- name: add calico policy for frontend and database access
  command: calicoctl apply -f /opt/configs/policy-postgres.yaml

