---
- name: create calico config directories
  file: 
    path: "{{ item }}"
    state: directory
  with_items:
    - /opt/configs/
    - /opt/configs/policies
    - /opt/configs/ippools


- name: copy calico ippools configurations
  copy: 
    src: ippools
    dest: /opt/configs/


- name: copy calico policies configurations
  template: 
    src: policies/hostaccess.yaml
    dest: /opt/configs/policies/hostaccess.yaml


- name: add calico frontend network ip pool
  command: calicoctl apply -f /opt/configs/ippools/frontend.yaml


- name: add calico backend network ip pool
  command: calicoctl apply -f /opt/configs/ippools/backend.yaml



- name: add calico backend docker network
  docker_network:
    name: backend
    driver: calico
    ipam_driver: calico-ipam
    ipam_options:
      subnet: '172.16.100.0/24'
    state: present


- name: add calico frontend docker network
  docker_network:
    name: frontend
    driver: calico
    ipam_driver: calico-ipam
    ipam_options:
      subnet: '172.16.110.0/24'
    state: present


- name: add calico permission to allow docker hosts to access containers directly 
  command: calicoctl apply -f /opt/configs/policies/hostaccess.yaml

